import type { GlobalThemeOverrides } from 'naive-ui';
export declare const colors: {
    primaryColor: string;
    primaryColorHover: string;
    primaryColorPressed: string;
    infoColor: string;
    infoColorHover: string;
    infoColorPressed: string;
    successColor: string;
    successColorHover: string;
    successColorPressed: string;
    errorColor: string;
    errorColorHover: string;
    errorColorPressed: string;
    warningColor: string;
    warningColorHover: string;
    warningColorPressed: string;
    textColorDisabled: string;
    textColor1: string;
    textColor2: string;
};
export declare const themeOverridesLight: GlobalThemeOverrides;
